[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dftorch"
version = "0.1.3"
description = "A Density Functional Tight Binding (SCC-DFTB) implementation in PyTorch"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "scipy",
  "torch",
  "setuptools",
  "pytest",
  "pandas"]

[project.optional-dependencies]
dev = ["ruff", "mypy", "pre-commit"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["-ra", "-q"]

[tool.ruff]
exclude = [
  "src/dftorch/_legacy",
]
